version: "3.8"
services:
    #PHP Service
    php:
        build:
            context: .
            target: php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "80:8000"


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8051:80
        environment:
            - PMA_HOST=65.1.113.208
            - PMA_PORT=3306





