version: "3.8"
services:
    #PHP Service
    nginx:
        image: nginx:alpine
        container_name: komiut-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
        restart: always
        depends_on:
            - komiut-app-1
            - komiut-app-2
            - 2safiri-app-1
            - 2safiri-app-2


    komiut-app-1:
        build:
            context: .
            dockerfile: Docker/Komiut/Dockerfile
            target: php
        image: komiut
        container_name: komiut-app-1
        working_dir: /var/www
        volumes:
            - ./Docker/Komiut/storage:/var/www/storage
        ports:
            - "8001"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8001" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
    komiut-app-2:
        image: komiut
        container_name: komiut-app-2
        working_dir: /var/www
        volumes:
            - ./Docker/Komiut/storage:/var/www/storage
        ports:
            - "8001"
        depends_on:
            - komiut-app-1
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8001" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s

    2safiri-app-1:
        build:
            context: .
            dockerfile: Docker/2safiri/Dockerfile
            target: php
        image: 2safiri
        container_name: 2safiri-app-1
        working_dir: /var/www
        volumes:
            - ./Docker/2safiri/storage:/var/www/storage
        ports:
            - "8000"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
    2safiri-app-2:
        image: 2safiri
        container_name: 2safiri-app-2
        working_dir: /var/www
        volumes:
            - ./Docker/2safiri/storage:/var/www/storage
        ports:
            - "8000"
        depends_on:
            - 2safiri-app-1
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s

    scheduler:
        container_name: komiut_scheduler
        image: komiut
        depends_on:
            - komiut-app-1
        volumes:
            - ./Docker/Scheduler/storage:/var/www/storage
        working_dir: /var/www
        restart: always
        entrypoint: [ "/var/www/Docker/Scheduler/schedule-runner.sh" ]
        healthcheck:
            test: ["CMD", "php", "artisan", "about"]
            interval: 60s
            timeout: 10s
            retries: 3

volumes:
    laravel-sessions:



