events {}

http {
    upstream komiut_app {
        server komiut-app-1:8001;
        server komiut-app-2:8001;
    }

    upstream 2safiri_app {
        server 2safiri-app-1:8000;
        server 2safiri-app-2:8000;
    }

    # Route for komiut.com
    server {
        listen 80;
        server_name komiut.com www.komiut.com;

        location / {
            proxy_pass http://komiut_app;

            # Forward client information
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Ensure only correct cookies are passed
            proxy_cookie_domain 2safiri.co.ke off;
            proxy_cookie_domain komiut.com komiut.com;
        }
    }

    # Route for 2safiri.co.ke
    server {
        listen 80;
        server_name 2safiri.co.ke www.2safiri.co.ke;

        location / {
            proxy_pass http://2safiri_app;

            # Forward client information
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Ensure only correct cookies are passed
            proxy_cookie_domain komiut.com off;
            proxy_cookie_domain 2safiri.co.ke 2safiri.co.ke;
        }
    }

     server {
            listen 80;

            location / {
                proxy_pass http://komiut_app;

                # Forward client information
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # Ensure only correct cookies are passed
                proxy_cookie_domain 2safiri.co.ke off;
                proxy_cookie_domain komiut.com komiut.com;
            }
        }
}
