events {}

http {
    upstream komiut_app {
        server komiut-app-1:8001;
        server komiut-app-2:8001;
    }

    upstream 2safiri_app {
        server 2safiri-app-1:8000;
        server 2safiri-app-2:8000;
    }

    # Route for komiut.com
    server {
        listen 80;
        server_name komiut.com www.komiut.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name komiut.com www.komiut.com;

        ssl_certificate /etc/letsencrypt/live/komiut.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/komiut.com/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://komiut_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }


    # Route for 2safiri.co.ke

    server {
        listen 80;
        server_name 2safiri.co.ke www.2safiri.co.ke;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name 2safiri.co.ke www.2safiri.co.ke;

        ssl_certificate /etc/letsencrypt/live/2safiri.co.ke/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/2safiri.co.ke/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://2safiri_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }



}
